""" Task 2 stuff """

MACROS = [
          'get_out_of_startbox',
          'pickup_array_prep',
          'pickup_array_move_feet',
          'pickup_array_move_hand_start',
          'pickup_array_move_hand_under',
          'pickup_array_grab',
          'pickup_array_lift',
          'spin_array',
          'drop_array_look_for_choke',
          'drop_array_get_ready',
          'drop_array_look_for_choke_2',
          'drop_array_move_feet',
          'drop_array_lookat_choke_again',
          'drop_array_perform_drop',
          'open_array_prep',
          'open_array_look_for_button',
          'open_array_reach_above',
          'open_array_press_button',
          'open_array_lift_hand',
          'pickup_cable_prep',
          'pickup_cable_look_for_choke',
          'pickup_cable_move_feet',
          'pickup_cable_move_hand_start',
          'pickup_cable_move_hand_finish',
          'pickup_cable_lift',
          'pickup_cable_grab',
          'plugin_look_for_plug',
          'plugin_move_feet',
          'plugin_move_hand_pre_start',
          'plugin_move_hand_start',
          'plugin_move_hand_finish',
          'plugin_letitgo',
          'task2_finish_box']
