""" Task 3 stuff """

MACROS = ['find_stairs', 'climb_stairs', 'approach_door',
          'unlock_door', 'open_door', 'enter_habitat',
          'walk_to_table',
          'rake_prepare',
          'rake_move_feet',
          'rake_start',
          'rake_back',
          'rake_finish',
          'spin_and_drop_repair_tool',
          'spin_and_drop_detector',
          'pickup_detector_prep',
          'pickup_detector_move_feet',
          'pickup_detector_hand_start',
          'pickup_detector_grab',
          'pickup_detector_all_done',
          'pickup_repair_tool_roll_prep',
          'pickup_repair_tool_roll_away',
          'pickup_repair_tool_prep',
          'pickup_repair_tool_vision_set_angle',
          'pickup_repair_tool_one_point_move_feet',
          'pickup_repair_tool_one_point_start',
          'pickup_repair_tool_one_point_grab',
          'pickup_repair_tool_one_point_standup',
          'pickup_repair_tool_move_feet',
          'pickup_repair_tool_hand_start',
          'pickup_repair_tool_grab',
          'pickup_repair_tool_test_grip',
          'pickup_repair_tool_all_done',
          'walk_to_wall',
          'move_to_sweep_start',
          'perform_sweep',
          'repair_position',
          'repair_pepper_wall',
         ]
